# Generated by Django 5.1.7 on 2025-04-09 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productimageassociation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_associations', to='api.product'),
        ),
        migrations.AlterField(
            model_name='productimageassociation',
            name='product_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_associations', to='api.productimage'),
        ),
    ]
