# Generated by Django 5.1.7 on 2025-04-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimageassociation',
            unique_together={('product', 'product_image')},
        ),
    ]
